### ISSUE TITLE
Verify transfer key contract

### ISSUE THREAD

**Issue by CrossField1973** [LucK1Y/Padlock-Token#12]

**Comment by LucK1Y** [comment]
contract muss angepasst werden:  
    function transferKey(string memory pub_key_new_owner, string memory lock_id) public returns (bool) {

        //TODO: Check that only correct owner can invoke this methode
        //!!!msg.sender != pub_key 
        
        _ownerTable[lock_id]=pub_key_new_owner;

        return true;
    }

**Comment by LucK1Y** [comment]
#16 contract changed
