### ISSUE TITLE
Chain-Registration site doesn't display whole id

### ISSUE THREAD

**Issue by CrossField1973** [LucK1Y/Padlock-Token#7]

**Comment by LucK1Y** [comment]
Changed text **p** to **pre** raw text
=> shows unformated complete string and tested
changed in this commit: [here](https://github.com/LucK1Y/Padlock-Token/commit/93072d9f5a652f2e0014f1445dcc6e7076cbeac8#diff-501c50fc3b96dbdfacd958d46363adf7ccd202218e3339af36457b5ef2bbac44)
